#!/usr/bin/env bash

source "$HOME/.config/crisidev-common"

declare -a arr=(
  "workspace 2:  "
)
i3_msg_dispatcher "${arr[@]}"

killall imwheel || true

set_audio alsa_input.pci-0000_04_00.6.analog-stereo alsa_output.pci-0000_04_00.6.analog-stereo

xset +dpms
restart_night_light

finish_autorandr_switch laptop
