#!/usr/bin/env bash
unameOut="$(uname -s)"
workDir=$(dirname "$0")
cd "$workDir" || exit 1 # cd to directory with flake
case "${unameOut}" in
    Linux*)     nix run home-manager -- --impure --flake .\#$(hostname -s) "$@";;
    *)          echo "Unknown system $unameOut" && exit 1;;
esac
