#!/usr/bin/env bash
unameOut="$(uname -s)"
workDir=$(dirname "$0")
cd "$workDir" || exit 1 # cd to directory with flake
if [ "$1" = "pull" ]; then
    nix flake update
    if [ "$2" = "--all" ]; then
        cd ./home-nix/programs/node-packages && ./update-node-pkgs
    fi
else
    case "${unameOut}" in
	Linux*) 
	    if which nom > /dev/null; then
	        nix run -L home-manager -- --impure --flake ".#$(hostname -s)" "$@" |& nom 
	    else
	        nix run -L home-manager -- --impure --flake ".#$(hostname -s)" "$@"
	    fi
	;;
        *) echo "Unknown system $unameOut" && exit 1 ;;
    esac
fi
