idle_bg = "#24283b"
idle_fg = "#c0caf5"
info_bg = "#7aa2f7"
info_fg = "#1f2335"
good_bg = "#9ece6a"
good_fg = "#1f2335"
warning_bg = "#ff9e64"
warning_fg = "#1f2335"
critical_bg = "#f7768b"
critical_fg = "#1f2335"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#11111100"
alternating_tint_fg = "#11111100"
