#!/usr/bin/env bash

source "$HOME/.config/crisidev-common"
declare -a arr=(
  "workspace 1:  , move workspace to output HDMI-A-0"
  "workspace 2:  , move workspace to output HDMI-A-0"
  "workspace 3:  , move workspace to output eDP"
  "workspace 4:  , move workspace to output eDP"
  "workspace 5:  , move workspace to output eDP"
  "workspace 6:  , move workspace to output HDMI-A-0"
  "workspace 7:  , move workspace to output HDMI-A-0"
  "workspace 8:  , move workspace to output eDP"
  "workspace 9:  , move workspace to output eDP"
  "workspace 10:  , move workspace to output HDMI-A-0"
  "workspace 11:  , move workspace to output HDMI-A-0"
  "workspace 12:  , move workspace to output HDMI-A-0"
  "workspace 13:  , move workspace to output eDP"
  "workspace 9:  "
  "workspace 2:  "
)
i3_msg_dispatcher "${arr[@]}"

imwheel -k

xset -dpms
restart_night_light

xrandr --output HDMI-A-0 --gamma 0:0:0

finish_autorandr_switch work
