[tools]
# language build
gradle = "latest"
meson = "latest"
ninja = "latest"

# language runtimes
python = "3.11.6"
java = "corretto-17"
golang = "1.21.3"
node = "20.9.0"
ruby = "3.2.2"

# tools
neovim = "nightly"
# fzf = "latest"
# gitui = "latest"
lazygit = "latest"
awscli = "latest"
usage = "latest"

[settings]
# configure `mise install` to always keep the downloaded archive
always_keep_download = false        # deleted after install by default
always_keep_install = false         # deleted on failure by default

# configure how frequently (in minutes) to fetch updated plugin repository changes
# this is updated whenever a new runtime is installed
# (note: this isn't currently implemented but there are plans to add it: https://github.com/jdx/mise/issues/128)
plugin_autoupdate_last_check_duration = '1 week' # set to 0 to disable updates

verbose = false     # set to true to see full installation output, see `MISE_VERBOSE`
asdf_compat = false # set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
jobs = 8            # number of plugins or runtimes to install in parallel. The default is `4`.
raw = false         # set to true to directly pipe plugins to stdin/stdout/stderr
yes = false         # set to true to automatically answer yes to all prompts

not_found_auto_install = true # see MISE_NOT_FOUND_AUTO_INSTALL
task_output = "prefix" # see Tasks Runner for more information
paranoid = false       # see MISE_PARANOID

shorthands_file = '~/.config/mise/shorthands.toml' # path to the shorthands file, see `MISE_SHORTHANDS_FILE`
disable_default_shorthands = false # disable the default shorthands, see `MISE_DISABLE_DEFAULT_SHORTHANDS`

experimental = true # enable experimental features

# configure messages displayed when entering directories with config files
status = {missing_tools = "if_other_versions_installed", show_env = false, show_tools = false}
python_compile = true
