[theme]
name = "slick"

[icons]
name = "awesome5"

[[block]]
block = "focused_window"
show_marks = "none"
max_width = 800

# [[block]]
# block = "bluetooth"
# # mac = "38:18:4C:2B:14:99"  # sony
# mac = "0C:C4:13:F8:76:65"  # pixel 
# format = ""
# format_unavailable = ""

[[block]]
block = "custom"
cycle = ["~/.bin/i3mute get"]
on_click = "~/.bin/i3mute set"
json = true
interval = 2

[[block]]
block = "custom"
cycle = ["~/.bin/i3exit dunst get"]
on_click = "~/.bin/i3exit dunst set"
hide_when_empty = false
json = true
interval = 2

[[block]]
block = "custom"
cycle = ["~/.bin/i3bluetooth"]
on_click = "~/.bin/i3bluetooth cycle"
hide_when_empty = false
json = true
interval = 2

[[block]]
block = "custom"
cycle = ["~/.bin/i3vpn"]
on_click = "~/.bin/i3vpn cycle"
hide_when_empty = false
json = true
interval = 5

# [[block]]
# block = "weather"
# format = "{weather} ({location}) {temp}, {wind} m/s {direction}"
# service = { name = "openweathermap", city_id = "2643743", units = "metric" }  # london
# service = { name = "openweathermap", city_id = "3169522", units = "metric" }  # reggio

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]
dynamic_width = false
max_width = 25
format = "{artist} - {title}"
hide_when_empty = true

[[block]]
block = "custom"
cycle = ["~/.bin/mwhandle"]
on_click = "~/.bin/mwhandle"
json = true
hide_when_empty = false
interval = 60

[[block]]
block = "custom"
cycle = ["~/.bin/khandle"]
on_click = "~/.bin/khandle"
hide_when_empty = false
json = true
interval = 60
