[theme]
name = "slick"

[icons]
name = "awesome5"

[[block]]
block = "focused_window"
show_marks = "none"
max_width = 800

[[block]]
block = "custom"
cycle = ["~/.bin/khandle"]
on_click = "~/.bin/khandle"
interval = 60

[[block]]
block = "custom"
cycle = ["~/.bin/i3vpn"]
on_click = "~/.bin/i3vpn cycle"
hide_when_empty = false
json = true
interval = 5

[[block]]
block = "custom"
cycle = ["~/.bin/mute-toggle get"]
on_click = "~/.bin/mute-toggle set"
json = true
interval = 2

[[block]]
block = "custom"
cycle = ["~/.bin/i3exit dunst get"]
on_click = "~/.bin/i3exit dunst set"
json = true
interval = 2

# [[block]]
# block = "xrandr"
# icons = false
# resolution = false
# interval = 30
# step_width = 5

[[block]]
block = "bluetooth"
mac = "38:18:4C:2B:14:99"  # sony
format = ""
format_unavailable = ""

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}, {wind} m/s {direction}"
service = { name = "openweathermap", city_id = "2643743", units = "metric" }  # london
