[theme]
theme = "tokyo"
[theme.overrides]
separator = "<span font_family='MonoLisaCrisidev Nerd Font' font='13.3'></span>"

[icons]
icons = "awesome6"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:500) |"
short = " $title.str(max_w:50) |"

# [[block]]
# block = "bluetooth"
# # mac = "38:18:4C:2B:14:99"  # sony
# mac = "0C:C4:13:F8:76:65"  # pixel 
# format = ""
# format_unavailable = ""
# [[block]]
# block = "github"
# token = "$GITHUB_TOKEN"
# format = " $icon $total.eng(1) "
# info = ["total"]
# warning = ["mention","review_requested"]
# hide_if_total_is_zero = true


[[block]]
block = "custom"
json = true
interval = 2
cycle = ["~/.bin/i3mute get"]
[[block.click]]
button = "left"
cmd = "~/.bin/i3mute set"

[[block]]
block = "custom"
json = true
interval = 5
cycle = ["~/.bin/i3bluetooth"]
[[block.click]]
button = "left"
cmd = "~/.bin/i3bluetooth cycle"

[[block]]
block = "custom"
cycle = ["~/.bin/i3vpn"]
json = true
interval = 5
[[block.click]]
button = "left"
cmd = "~/.bin/i3vpn cycle"

# [[block]]
# block = "weather"
# format = "{weather} ({location}) {temp}, {wind} m/s {direction}"
# service = { name = "openweathermap", city_id = "2643743", units = "metric" }  # london
# service = { name = "openweathermap", city_id = "3169522", units = "metric" }  # reggio
[[block]]
block = "custom"
json = true
interval = 60
cycle = ["~/.bin/mwhandle"]
[[block.click]]
button = "left"
cmd = "~/.bin/mwhandle"

[[block]]
block = "custom"
json = true
interval = 60
cycle = ["~/.bin/khandle"]
[[block.click]]
button = "left"
cmd = "~/.bin/khandle"

[[block]]
block = "github"
format = " $icon  $total.eng(w:1)  "
info = ["total"]
warning = ["mention", "review_requested"]
critical = ["assign", "security_alert"]
hide_if_total_is_zero = false

[[block]]
block = "notify"
format = " {$paused{}|} "

# [[block]]
# block = "music"
# player = "spotify"
# format = " $icon {$combo.str(max_w:20) $play $next |}"

# [[block]]
# block = "xrandr"
# format = " $icon "

[[block]]
block = "custom"
interval = 5
cycle = ["~/.bin/i3notify-chime"]
hide_when_empty = true
