[theme]
theme = "tokyo"
[theme.overrides]
separator = "<span font_family='MonoLisaCrisidev Nerd Font' font='13.3'></span>"

[icons]
icons = "awesome6"

# [[block]]
# block = "custom"
# command = "~/.bin/get_disk_io -R\"/^nvme.*/\" -t 1 |tail -n 1"
# interval = 3

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = " $icon $available ($percentage) "
format_alt = " $icon $available / $total ($percentage) "
alert_unit = "GB"
interval = 30
warning = 20.0
alert = 10.0

[[block]]
block = "net"
format = " $icon  {$ssid|$device}  $speed_down  $speed_up"
interval = 5

[[block]]
block = "memory"
format = " $icon$mem_avail.eng(3,B,M) ($mem_avail_percents.eng(2)) "
format_alt = " $icon_swap $swap_free.eng(3,B,M) ($swap_used_percents.eng(2))"
interval = 10
warning_mem = 70
warning_swap = 70
critical_mem = 90
critical_swap = 90

[[block]]
block = "cpu"
interval = 2
format = " $icon $utilization $barchart $boost "

# [[block]]
# block = "custom"
# cycle = ["~/.bin/i3cpu"]
# interval = 5

[[block]]
block = "load"
format = " $icon $5m "
interval = 3

[[block]]
block = "temperature"
interval = 5
good = 30
idle = 50
info = 75
warning = 90
format = " $icon $average "
chip = "k10temp-pci-00c3"

[[block]]
block = "battery"
info = 80
good = 60
warning = 40
critical = 20
driver = "upower"
format = " $icon $power $time ($percentage) "
interval = 30

[[block]]
block = "time"
interval = 2
locale = "en_US"
[block.format]
full = " $icon %a %d %b %T "
short = " $icon %R "
