[theme]
name = "slick"

[icons]
name = "awesome5"

# [[block]]
# block = "custom"
# command = "~/.bin/get_disk_io -R\"/^nvme.*/\" -t 1 |tail -n 1"
# interval = 3

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
format = "{alias} {available}"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "custom"
cycle = ["~/.bin/i3vpn"]
on_click = "~/.bin/i3vpn cycle"
hide_when_empty = false
interval = 5

[[block]]
block = "net"
device = "wlp1s0"
format = "{ssid} {speed_up} {speed_down}"
interval = 5

[[block]]
block = "net"
device = "enp0s31f6"
interval = 5

[[block]]
block = "memory"
format_mem = "{mem_avail;M}"
format_swap = "{swap_free;M}"
display_type = "memory"
icons = true
clickable = true
interval = 10
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
warning = 60
critical = 90
interval = 2
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "custom"
cycle = ["~/.bin/i3cpu"]
on_click = "~/.bin/i3cpu cycle"
interval = 5

[[block]]
block = "load"
format = "{1m}"
interval = 5

[[block]]
# block = "custom"
# cycle = ["sensors |grep Package |awk '{print $4}' |sed 's#+##g' |sed 's#C##g'"]
# interval = 5
[[block]]
block = "temperature"
collapsed = false
interval = 10
good = 40
idle = 60
info = 80
warning = 90
chip = "*-isa-*"
format = "{average}"

[[block]]
block = "battery"
driver = "upower"
format = "{time} ({percentage})"
interval = 30

[[block]]
block = "time"
interval = 1
format = "%a %d %b %T"
