[theme]
name = "slick"

[icons]
name = "awesome5"

# [[block]]
# block = "custom"
# command = "~/.bin/get_disk_io -R\"/^nvme.*/\" -t 1 |tail -n 1"
# interval = 3

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
format = "{alias} {available}"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlp1s0"
format = "{ssid} {speed_up} {speed_down}"
interval = 5
hide_inactive = true

[[block]]
block = "net"
device = "eno1"
interval = 5
hide_inactive = true

[[block]]
block = "memory"
format_mem = "{mem_avail;M}"
format_swap = "{swap_free;M}"
display_type = "memory"
icons = true
clickable = true
interval = 10
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
warning = 60
critical = 90
interval = 2
format = "{barchart} {utilization} {frequency} {boost}"

# [[block]]
# block = "custom"
# cycle = ["~/.bin/i3cpu"]
# interval = 5

[[block]]
block = "load"
format = "{1m}"
interval = 3

[[block]]
block = "temperature"
collapsed = false
interval = 10
good = 30
idle = 50
info = 75
warning = 90
chip = "k10temp-pci-00c3"
format = "{average}"

[[block]]
block = "battery"
driver = "upower"
format = "{time} ({percentage})"
interval = 30

[[block]]
block = "time"
interval = 1
format = "%a %d %b %T"
