#!/usr/bin/env bash

i3_msg_dispatcher() {
  arr=${1}
  for cmd in "${arr[@]}"; do
    i3-msg "${cmd}"
    sleep 0.1
  done
}

notify() {
  notify-send -i display "Display profile" "$1"
}

finish_autorandr_switch() {
  # Disable tit
  xinput -set-prop "PS/2 Generic Mouse" "Device Enabled" 0
  # Setup keyboard
  setup_keyboard_speed
  # Setup background
  feh --bg-fill "${HOME}/Pictures/wallpapers/fishing.jpeg"
  notify "$1"
}

display_off() {
  xrandr --output VIRTUAL-1 --off --output eDP-1 --off \
    --output DP-1 --off --output DP-2 --off --output DP-2-1 \
    --off --output DP-2-2 --off --output HDMI-1 --off --output HDMI-2 --off
}

# set keyboard speed
setup_keyboard_speed() {
  xset r rate 200 60
  xset m 2 60
  xset b off
}
