set_title = true
display_time = true
disable = [
    "system",
    "flatpak",
    "snap",
    "gnome_shell_extensions",
    "containers",
    "nix",
    "toolbx",
    "pnpm"
]
ignore_failures = ["git_repos"]

[git]
max_concurrency = 5
repos = [
    # Password store
    "~/.password-store",
    # Home sick
    "~/.homesick/repos/homeshick",
    "~/.homesick/repos/dotfiles",
    "~/.homesick/repos/MatbigoiDotFiles",
    # Updates
    "~/github/0updates/dunst",
    "~/github/0updates/i3-gnome",
    "~/github/0updates/keyd",
    "~/github/0updates/neovide",
    "~/github/0updates/unclutter-xfixes",
    "~/github/0updates/xedgewarp",
    "~/github/0updates/dog",
    "~/github/0updates/rofi-themes",
    "~/github/0updates/rofi-source",
    "~/github/0updates/bitwarden-rofi",
    "~/github/0updates/rofi-emoji",
    "~/github/0updates/picom",
]
arguments = "--ff-only --rebase --autostash"

[commands]
"Amzn toolbox" = "toolbox update"

[python]
enable_pip_review = true
