[misc]
set_title = true
display_time = true
disable = [
    "system",
    "flatpak",
    "snap",
    "gnome_shell_extensions",
    "containers",
    "nix",
    "toolbx",
    "pnpm"
]
ignore_failures = ["git_repos"]

[git]
max_concurrency = 5
repos = [
    # Home sick
    "~/.homesick/repos/homeshick",
    "~/.homesick/repos/dotfiles",
    "~/.homesick/repos/lvim",
    # Updates
    "~/github/yabai",
]
arguments = "--ff-only --rebase --autostash"

[python]
enable_pip_review = true
