[misc]
set_title = true
display_time = true
disable = ["home_manager", "pnpm", "poetry", "snap", "system", "toolbx", "uv"]
ignore_failures = ["git_repos"]

[git]
max_concurrency = 5
repos = [
    # Home sick
    "~/.homesick/repos/homeshick",
    "~/.homesick/repos/dotfiles",
    "~/.homesick/repos/lazyvim",
    "~/github/gnome-shell-extensions/mouse-follows-focus",
    "~/github/gnome-shell-extensions/pop-shell",
    "~/github/Tokyonight-GTK-Theme",
]
arguments = "--ff-only --rebase --autostash"

[python]
enable_pip_review = true
