set_title = false
disable = ["system", "flatpak", "snap", "gnome_shell_extensions", "pnpm", "containers"]
ignore_failures = ["git_repos"]

[git]
max_concurrency = 5
repos = [
    # Zsh
    "~/.zprezto",
    # Password store
    "~/.password-store",
    # Envs
    "~/.nodenv",
    "~/.pyenv",
    "~/.rbenv",
    "~/.goenv",
    # Home sick
    "~/.homesick/repos/homeshick",
    "~/.homesick/repos/dotfiles",
    "~/.homesick/repos/MatbigoiDotFiles",
    # Updates
    "~/github/smithy-language-server",
    "~/github/0updates/dunst",
    "~/github/0updates/i3-gnome",
    "~/github/0updates/keyd",
    "~/github/0updates/neovide",
    "~/github/0updates/unclutter-xfixes",
    "~/github/0updates/xedgewarp",
    "~/github/0updates/dog",
    "~/github/0updates/joycond",
    "~/github/0updates/joycond-cemuhook",
]
arguments = "--ff-only --rebase --autostash"

[commands]
"Pip packages" = "pip-review -a"
"Amzn toolbox" = "toolbox update"
