{ ... }:
let
  # Desktop-file ids for the apps actually installed on falcon (flatpak / nix /
  # system / repo-managed), so no default points at a missing app.
  firefox = "org.mozilla.firefox.desktop"; # flatpak
  feh = "feh.desktop"; # nix
  nautilus = "org.gnome.Nautilus.desktop"; # system GNOME
  calibre = "com.calibre_ebook.calibre.desktop"; # flatpak
  signal = "org.signal.Signal.desktop"; # flatpak
  bitwarden = "com.bitwarden.desktop.desktop"; # flatpak
  ferdium = "org.ferdium.Ferdium.desktop"; # flatpak
  spotify = "com.spotify.Client.desktop"; # flatpak
  # mailto handler is a Chrome Gmail PWA. NOTE: this id is generated by Chrome per
  # profile — it is NOT reproducible on a fresh machine (unlike everything else
  # here). Swap to `firefox` if you want a portable default.
  gmail = "chrome-faolnafnngnfdaknnbpnkhgohbobgegn-Default.desktop";

  images = [
    "image/png"
    "image/jpeg"
    "image/gif"
    "image/webp"
    "image/bmp"
    "image/tiff"
  ];
  # Types the browser owns (web docs + xml/feeds + web media).
  webTypes = [
    "text/html"
    "application/xhtml+xml"
    "text/xml"
    "application/xml"
    "application/rss+xml"
    "application/rdf+xml"
  ];
  # Local video: no dedicated player is installed, so the browser is the fallback.
  videoTypes = [
    "video/webm"
    "video/mp4"
    "video/x-matroska"
  ];
in
{
  # Declarative default apps → ~/.config/mimeapps.list. Rebuilt from the old
  # homesick file and made complete + sane:
  #   - dropped the Slack scheme (Slack isn't installed — Ferdium covers it)
  #   - dropped the GNOME `custom-desktop-starter.342765` cruft from text/plain
  #   - added real defaults for PDF (zathura), ebooks (calibre), images (feh,
  #     was the browser), folders (nautilus), and the spotify: scheme
  # NOTE: home-manager makes mimeapps.list a read-only symlink, so GUI "set as
  # default" buttons won't persist — change defaults here instead.
  xdg.mimeApps = {
    enable = true;

    defaultApplications =
      {
        # Web + feeds + browser-only schemes
        "x-scheme-handler/http" = firefox;
        "x-scheme-handler/https" = firefox;
        "x-scheme-handler/ftp" = firefox;
        "x-scheme-handler/chrome" = firefox;
        "application/x-xpinstall" = firefox;
        "image/svg+xml" = firefox; # svg renders better in the browser than feh

        # Mail (Chrome Gmail PWA — see note above)
        "x-scheme-handler/mailto" = gmail;

        # Documents & books (PDF opens in firefox — its viewer works well)
        "application/pdf" = firefox;
        "application/epub+zip" = calibre;
        "application/x-mobipocket-ebook" = calibre;

        # Folders
        "inode/directory" = nautilus;

        # App URI schemes
        "x-scheme-handler/bitwarden" = bitwarden;
        "x-scheme-handler/ferdium" = ferdium;
        "x-scheme-handler/sgnl" = signal;
        "x-scheme-handler/signalcaptcha" = signal;
        "x-scheme-handler/spotify" = spotify;
      }
      // builtins.listToAttrs (map (t: {
        name = t;
        value = firefox;
      }) webTypes)
      // builtins.listToAttrs (map (t: {
        name = t;
        value = feh;
      }) images)
      // builtins.listToAttrs (map (t: {
        name = t;
        value = firefox;
      }) videoTypes);

    # Register firefox as an available (non-default) opener for local images/video
    # too (images default to feh), so it still shows up in "Open With".
    associations.added = builtins.listToAttrs (map (t: {
      name = t;
      value = firefox;
    }) (images ++ videoTypes));
  };
}
