{ ... }:
{
  # zellij — ported from home/.config/zellij. config.kdl is a large autogenerated
  # KDL file (full keybind set); translating it to nix attrs via settings would be
  # lossy, so it's passed through byte-for-byte via extraConfig (readFile). The
  # theme is provided via the native themes option (written to
  # ~/.config/zellij/themes/tokyonight_storm.kdl), selected by `theme "…"` in the
  # config. Shell integration stays off (zsh is homesick-managed, no auto-attach),
  # matching the old setup.
  programs.zellij = {
    enable = true;
    extraConfig = builtins.readFile ../files/zellij/config.kdl;
    themes.tokyonight_storm = ../files/zellij/tokyonight_storm.kdl;
  };
}
