#!/usr/bin/env bash

WINDOW_ID=$1
GREEN=0xffa6da95
ORANGE=0xfff5a97f
RED=0xffed8796
BLUE=0xff95b5ff

QUERY=$(yabai -m query --windows --window "$WINDOW_ID")
FLOATING=$(echo "$QUERY" | jq '."is-floating"')
FULLSCREEN=$(echo "$QUERY" | jq '."has-fullscreen-zoom"')
STACKS=$(yabai -m query --windows --space |jq '[.[]."stack-index"] | add')

if [ "$FLOATING" = "true" ]; then
    borders active_color="glow($GREEN)"
elif [ "$FULLSCREEN" = "true" ]; then
    borders active_color="glow($ORANGE)"
elif [ "$STACKS" -gt 0 ]; then
    borders active_color="glow($RED)"
else
    borders active_color="glow($BLUE)"
fi

sketchybar --trigger window_focus
exit 0
