#!/usr/bin/env bash
LAYOUT=$(yabai -m query --spaces --space | jq -r .type)

case "$LAYOUT" in
    bsp)
        yabai -m space --layout stack
        LAYOUT=stack
        ;;
    stack)
        yabai -m space --layout float
        LAYOUT=float
        ;;
    float)
        yabai -m space --layout bsp
        LAYOUT=bsp
        ;;
esac

~/.bin/hs -c "return hs.helpers.notify('Layout set to $LAYOUT')"
