#!/bin/bash

if [ "$1" = "clockwise" ]; then
    win=$(yabai -m query --windows --window last | jq '.id')

    while :; do
        yabai -m window "$win" --swap prev &>/dev/null
        if [[ $? -eq 1 ]]; then
            break
        fi
    done
elif [ "$1" = "counterclockwise" ]; then

    win=$(yabai -m query --windows --window first | jq '.id')

    while :; do
        yabai -m window "$win" --swap next &>/dev/null
        if [[ $? -eq 1 ]]; then
            break
        fi
    done
fi
