#!/usr/bin/env bash

# set -x

# signals
yabai -m signal --add event=window_focused action="/opt/homebrew/bin/sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="/opt/homebrew/bin/sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="/opt/homebrew/bin/sketchybar --trigger windows_on_spaces"
## make all non resizable windows that
yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float --grid 3:3:1:1:1:1'

# global settings
# active_window_border_color 0xff007aff 0xffe1e3e4
yabai -m config mouse_follows_focus        on
yabai -m config focus_follows_mouse        autoraise
yabai -m config window_zoom_persist        off
yabai -m config window_placement           second_child
yabai -m config window_shadow              on
yabai -m config window_opacity             on
yabai -m config window_opacity_duration    0.15
yabai -m config active_window_opacity      1.0
yabai -m config normal_window_opacity      0.95
yabai -m config split_ratio                0.50
yabai -m config auto_balance               off

# paddings, bar and gaps
yabai -m config external_bar               all:35:0
yabai -m config top_padding                10
yabai -m config bottom_padding             8
yabai -m config left_padding               8
yabai -m config right_padding              8
yabai -m config window_gap                 8

# mouse settings
yabai -m config mouse_modifier             cmd
yabai -m config mouse_action1              move
yabai -m config mouse_action2              resize
yabai -m config mouse_drop_action          swap

# rename spaces
yabai -m space 1 --label terminal
yabai -m space 2 --label firefox
yabai -m space 3 --label outlook
yabai -m space 4 --label spotify
yabai -m space 5 --label teams
yabai -m space 6 --label whatsapp
yabai -m space 7 --label telegram
yabai -m space 8 --label signal
yabai -m space 9 --label videoconf

# application for desktop
yabai -m rule --add app="^Firefox$" space=2 sticky=off
yabai -m rule --add app="^Microsoft Outlook$" space=3
yabai -m rule --add app="^Microsoft Outlook$" title="^Calendar$" space=3
yabai -m rule --add app="^Spotify$" space=4
yabai -m rule --add app="^Microsoft Teams (work or school)$" space=6
yabai -m rule --add app="^WhatsApp$" space=7
yabai -m rule --add app="^Telegram$" space=8
yabai -m rule --add app="^Signal$" space=9

# rule
# unmanaged
yabai -m rule --add title="^Hammerspoon Console$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Font Book$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^iStat Menus$" manage=off sticky=off
yabai -m rule --add app="^Stats$" manage=off sticky=off
yabai -m rule --add app="^Company Portal$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add title="^float-term$" manage=off
yabai -m rule --add app="^Microsoft Outlook$" title="^Outlook Settings$" manage=off
yabai -m rule --add app="^Microsoft Outlook$" title="^Rules$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Bitwarden$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^The Unarchiver$" manage=off
yabai -m rule --add app="^AppCleaner$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Color Picker$" manage=off
yabai -m rule --add app="^Weather$" manage=off

# sticky
yabai -m rule --add app="^Digital Colou?r Meter$" manage=off

# layout
yabai -m config layout bsp

# reload sketchybar
"$HOME/.bin/hs" -c "return hs.helpers.cycle_all_spaces_mission_control()"
sleep 0.2
sketchybar --trigger mic_update window_focus front_app_switched wifi_change windows_on_space

# add borders
LANG="en_US.UTF-8" /opt/homebrew/opt/borders/bin/borders active_color=0xff939ab7 inactive_color=0xff494d64 width=4.0 2>/dev/null 1>&2 &

echo "yabai configuration loaded.."
