#!/usr/bin/env bash

source "$HOME/.config/crisidev-common"
declare -a arr=(
  "workspace 1:  , move workspace to output HDMI-A-0"
  "workspace 2:  , move workspace to output HDMI-A-0"
  "workspace 3:  , move workspace to output eDP"
  "workspace 4:  , move workspace to output eDP"
  "workspace 5:  , move workspace to output eDP"
  "workspace 6:  , move workspace to output HDMI-A-0"
  "workspace 7:  , move workspace to output HDMI-A-0"
  "workspace 8:  , move workspace to output eDP"
  "workspace 9:  , move workspace to output eDP"
  "workspace 10:  , move workspace to output HDMI-A-0"
  "workspace 11:  , move workspace to output HDMI-A-0"
  "workspace 12:  , move workspace to output HDMI-A-0"
  "workspace 13:  , move workspace to output eDP"
  "workspace 9:  "
  "workspace 2:  "
)
i3_msg_dispatcher "${arr[@]}"

imwheel -k

set_audio alsa_input.usb-21102019_THRONMAX_PULSE_MICROPHONE-00.iec958-stereo alsa_output.pci-0000_04_00.1.hdmi-stereo

xset -dpms
restart_night_light

finish_autorandr_switch home
