#!/usr/bin/env bash

# Input validation
if [[ -z $1 ]]; then
    echo "Usage: $0 <workspace-number>|startup|rebalance"
    exit 1
fi

WORKSPACE=$1

# File to store the previous and current workspace states
STATE_FILE="/tmp/.workspace_toggle_state"

# Windows and workspaces mappings
declare -A WINDOWS
WINDOWS["firefox-esr-esr128"]=1
WINDOWS["ferdium"]=4
WINDOWS["org.signal.Signal"]=3
WINDOWS["spotify"]=2

focus_workspace() {
    gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval \
        "global.workspace_manager.get_workspace_by_index($1).activate(global.get_current_time());"
}

if [ "$WORKSPACE" = "startup" ]; then
    sleep 1
    gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval "Main.overview.hide();"
    exit 0
fi

if [ "$WORKSPACE" = "rebalance" ]; then
    dbus-send --session --dest=org.gnome.Shell --print-reply=literal /org/gnome/Shell/Extensions/Windows org.gnome.Shell.Extensions.Windows.List | jq -c '.[]' | while read -r window; do
        wm_class=$(echo "$window" | jq -r '.wm_class_instance')
        id=$(echo "$window" | jq -r '.id')
        if [[ -v WINDOWS["$wm_class"] ]]; then
            workspace=${WINDOWS["$wm_class"]}
            echo "Moving window $wm_class to workspace $workspace"
            gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.MoveToWorkspace "$id" "$workspace"
        fi
    done
    notify-send -a "Focus Switch" -i settings "All windows rebalanced"
    exit 0
fi

# Retrieve previous and current workspace states
PREVIOUS_WORKSPACE=""
CURRENT_WORKSPACE=""

if [[ -f $STATE_FILE ]]; then
    read -r CURRENT_WORKSPACE PREVIOUS_WORKSPACE <"$STATE_FILE"
fi

# Toggle logic: switch back to the previous workspace if selecting the same workspace again
if [[ "$WORKSPACE" == "$CURRENT_WORKSPACE" ]]; then
    TARGET_WORKSPACE=$PREVIOUS_WORKSPACE
    echo "Toggling back to workspace: $PREVIOUS_WORKSPACE"
else
    TARGET_WORKSPACE=$WORKSPACE
    echo "Switching to workspace: $WORKSPACE"
fi

# Update the state file with the new states
echo "$TARGET_WORKSPACE $CURRENT_WORKSPACE" >"$STATE_FILE"

# Activate the target workspace using gdbus
focus_workspace "$TARGET_WORKSPACE"
