#!/usr/bin/env bash

export PATH=/usr/bin:$PATH

echo "[gsettings] starting system configuration"

# Extension schemas
echo "[gsettings] setting up gnome-extensions schemas"
rm -rf "$HOME/.local/share/glib-2.0/schemas"
mkdir -p "$HOME/.local/share/glib-2.0/schemas"
find "$HOME/.local/share/gnome-shell/extensions" -type f -name \*.gschema.xml -exec ln -sf {} "$HOME/.local/share/glib-2.0/schemas/" \;
glib-compile-schemas "$HOME/.local/share/glib-2.0/schemas"

# Cleanup
echo "[gsettings] cleaning up unused keys"
gsettings set org.gnome.mutter overlay-key ""
gsettings set org.gnome.mutter.keybindings cancel-input-capture "[]"
gsettings set org.gnome.shell.keybindings shift-overview-up "[]"
gsettings set org.gnome.shell.keybindings shift-overview-down "[]"
gsettings set org.gnome.shell.keybindings toggle-quick-settings "[]"
gsettings set org.gnome.shell.keybindings focus-active-notification "[]"
gsettings set org.gnome.desktop.wm.keybindings activate-window-menu "[]"
gsettings set org.gnome.desktop.wm.keybindings cycle-group "[]"
gsettings set org.gnome.desktop.wm.keybindings cycle-group-backward "[]"
gsettings set org.gnome.desktop.wm.keybindings cycle-windows "[]"
gsettings set org.gnome.desktop.wm.keybindings cycle-windows-backward "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-last "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "[]"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "[]"
gsettings set org.gnome.desktop.wm.keybindings panel-main-menu "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "[]"
gsettings set org.freedesktop.ibus.general.hotkey triggers "[]"
gsettings set org.freedesktop.ibus.panel.emoji hotkey "[]"
for x in {1..9}; do
    gsettings set org.gnome.shell.keybindings switch-to-application-"$x" "[]"
    gsettings set org.gnome.shell.keybindings open-new-window-application-"$x" "[]"
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-"$x" "[]"
    gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-"$x" "[]"
done

# Gnome general
echo "[gsettings] setting up gnome interface"
gsettings set org.gnome.shell.extensions.user-theme name "Orchis-Grey-Dark-Nord"
gsettings set org.gnome.desktop.interface gtk-theme "Orchis-Grey-Dark-Nord"
gsettings set org.gnome.desktop.interface icon-theme "Suru++"
gsettings set org.gnome.desktop.interface clock-show-seconds true
# gsettings set org.gnome.desktop.background picture-uri "file://$HOME/.homesick/repos/dotfiles/wallpapers/unsplash.jpg"
# gsettings set org.gnome.desktop.background picture-uri-dark "file://$HOME/.homesick/repos/dotfiles/wallpapers/unsplash.jpg"
# gsettings set org.gnome.desktop.screensaver picture-uri "file://$HOME/.homesick/repos/dotfiles/wallpapers/unsplash.jpg"
gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier "<Super>"
gsettings set org.gnome.desktop.wm.preferences focus-mode "mouse"
gsettings set org.gnome.desktop.wm.preferences auto-raise true
gsettings set org.gnome.desktop.wm.preferences theme "Orchis-Grey-Dark-Nord"
gsettings set org.gnome.desktop.wm.preferences workspace-names "[' ', ' ', ' ', ' ', '󰒱 ', ' ', ' ', ' ']"
gsettings set org.gnome.desktop.wm.preferences num-workspaces 8
gsettings set org.gnome.mutter workspaces-only-on-primary true
gsettings set org.gnome.mutter focus-change-on-pointer-rest false
gsettings set org.gnome.settings-daemon.plugins.power idle-brightness 240
gsettings set org.gnome.desktop.default-applications.terminal exec "$HOME/.nix-profile/bin/kitty"
gsettings set org.gnome.desktop.default-applications.terminal exec-arg "-e"
gsettings set org.gnome.desktop.peripherals.keyboard repeat true
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 14
gsettings set org.gnome.desktop.peripherals.keyboard delay 230
gsettings set org.gnome.desktop.sound event-sounds false
gsettings set org.gnome.desktop.sound input-feedback-sounds false
gsettings set org.gnome.desktop.sound theme-name "Yaru"
gsettings set org.gnome.desktop.peripherals.mouse natural-scroll false
gsettings set org.gnome.desktop.peripherals.touchpad edge-scrolling-enabled false
gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false
gsettings set org.gnome.desktop.peripherals.touchpad two-finger-scrolling-enabled true
gsettings set org.gnome.shell.extensions.dash-to-dock show-trash false
gsettings set org.gnome.nautilus.preferences thumbnail-limit 10485760

# Monitor detection
"$HOME/.bin/monitor-switch" now

# Gnome keybindings
echo "[gsettings] setting up gnome keybindings"
gsettings set org.gnome.shell.keybindings toggle-overview "['<Super>Space']"
gsettings set org.gnome.shell.keybindings toggle-application-view "['<Super><Alt>Space']"
gsettings set org.gnome.shell.keybindings toggle-message-tray "['<Alt><Super>n']"
gsettings set org.gnome.shell.keybindings screenshot "['<Shift>Print']"
gsettings set org.gnome.shell.keybindings screenshot-window "['<Alt>Print']"
gsettings set org.gnome.desktop.wm.keybindings close "['<Super>w']"
gsettings set org.gnome.desktop.wm.keybindings minimize "['<Super><Alt>comma']"
gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['<Super><Alt>f']"
gsettings set org.gnome.desktop.wm.keybindings panel-run-dialog "['<Alt>F2']"
gsettings set org.gnome.desktop.wm.keybindings switch-applications "['<Super>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "['<Shift><Super>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-group "['<Super>Above_Tab', '<Alt>Above_Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-group-backward "['<Shift><Super>Above_Tab', '<Shift><Alt>Above_Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "['<Shift><Alt>Tab']"
gsettings set org.gnome.mutter.keybindings switch-monitor "['<Super><Alt>d','XF86Display']"
gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver "['<Super><Alt>l']"
gsettings set org.gnome.settings-daemon.plugins.media-keys terminal "['<Super>Return']"

# Focus workspaces
echo "[gsettings] setting up custom workspace focus"
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "[ \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom9/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom10/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom11/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom12/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom13/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom14/', \
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom15/' \
]"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding "'<Super>Escape'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command "'$HOME/.bin/focus-switch 0'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name "'Switch focus to workspace 1'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding "'<Super>F2'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command "'$HOME/.bin/focus-switch 1'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name "'Switch focus to workspace 2'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding "'<Super>F1'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command "'$HOME/.bin/focus-switch 2'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name "'Switch focus to workspace 3'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/binding "'<Super>F3'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/command "'$HOME/.bin/focus-switch 3'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/name "'Switch focus to workspace 4'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/binding "'<Super>1'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/command "'$HOME/.bin/focus-switch 4'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/name "'Switch focus to workspace 5'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom14/binding "'<Super><Alt>1'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom14/command "'$HOME/.bin/focus-switch 4 force'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom14/name "'Force switch focus to workspace 5'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/binding "'<Super>2'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/command "'$HOME/.bin/focus-switch 5'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/name "'Switch focus to workspace 6'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/binding "'<Super>3'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/command "'$HOME/.bin/focus-switch 6'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/name "'Switch focus to workspace 7'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/binding "'<Super>4'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/command "'$HOME/.bin/focus-switch 7'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/name "'Switch focus to workspace 8'"

# Move window to workspace
echo "[gsettings] setting up moving windows to workspaces"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Super><Shift>Escape']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Super><Shift>F2']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Super><Shift>F1']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Super><Shift>F3']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5 "['<Super><Shift>1']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6 "['<Super><Shift>2']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-7 "['<Super><Shift>3']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-8 "['<Super><Shift>4']"

# Pop! Shell
echo "[gsettings] setting up pop-shell"
gsettings set org.gnome.shell.extensions.pop-shell activate-launcher "[]"
gsettings set org.gnome.shell.extensions.pop-shell pop-monitor-down "[]"
gsettings set org.gnome.shell.extensions.pop-shell pop-monitor-left "[]"
gsettings set org.gnome.shell.extensions.pop-shell pop-monitor-right "[]"
gsettings set org.gnome.shell.extensions.pop-shell pop-monitor-up "[]"
gsettings set org.gnome.shell.extensions.pop-shell pop-workspace-down "[]"
gsettings set org.gnome.shell.extensions.pop-shell pop-workspace-up "[]"
gsettings set org.gnome.shell.extensions.pop-shell snap-to-grid false
gsettings set org.gnome.shell.extensions.pop-shell active-hint true
gsettings set org.gnome.shell.extensions.pop-shell active-hint-border-radius 12
gsettings set org.gnome.shell.extensions.pop-shell hint-color-rgba "rgb(233,233,237)"
gsettings set org.gnome.shell.extensions.pop-shell tile-enter "['<Super><Alt>Backspace']"
gsettings set org.gnome.shell.extensions.pop-shell tile-accept "['Return']"
gsettings set org.gnome.shell.extensions.pop-shell tile-reject "['Escape']"
gsettings set org.gnome.shell.extensions.pop-shell tile-orientation "['<Super><Alt>o']"
gsettings set org.gnome.shell.extensions.pop-shell toggle-tiling "['<Super><Alt>y']"
gsettings set org.gnome.shell.extensions.pop-shell toggle-stacking-global "['<Super><Alt>s']"
gsettings set org.gnome.shell.extensions.pop-shell toggle-floating "['<Super><Alt>Backslash']"
gsettings set org.gnome.shell.extensions.pop-shell tile-move-down "[]"
gsettings set org.gnome.shell.extensions.pop-shell tile-move-left "[]"
gsettings set org.gnome.shell.extensions.pop-shell tile-move-right "[]"
gsettings set org.gnome.shell.extensions.pop-shell tile-move-up "[]"
gsettings set org.gnome.shell.extensions.pop-shell tile-swap-down "[]"
gsettings set org.gnome.shell.extensions.pop-shell tile-swap-left "[]"
gsettings set org.gnome.shell.extensions.pop-shell tile-swap-right "[]"
gsettings set org.gnome.shell.extensions.pop-shell tile-swap-up "[]"
gsettings set org.gnome.shell.extensions.pop-shell tile-resize-down "['Down']"
gsettings set org.gnome.shell.extensions.pop-shell tile-resize-left "['Left']"
gsettings set org.gnome.shell.extensions.pop-shell tile-resize-right "['Right']"
gsettings set org.gnome.shell.extensions.pop-shell tile-resize-up "['Up']"
gsettings set org.gnome.shell.extensions.pop-shell tile-move-down-global "['<Super><Alt>Down']"
gsettings set org.gnome.shell.extensions.pop-shell tile-move-left-global "['<Super><Alt>Left']"
gsettings set org.gnome.shell.extensions.pop-shell tile-move-right-global "['<Super><Alt>Right']"
gsettings set org.gnome.shell.extensions.pop-shell tile-move-up-global "['<Super><Alt>Up']"

# Custom keybinds
echo "[gsettings] setting up custom keybindings"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/binding "'<Ctrl>space'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/command "'nautilus'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/name "'Open nautilus file manager'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom9/binding "'<Super><Alt>e'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom9/command "'gnome-session-quit'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom9/name "'Quite Gnome session'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom10/binding "'<Super><Alt>m'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom10/command "'$HOME/.bin/clean-notifications'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom10/name "'Clean all notifications'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom11/binding "'<Super><Alt>p'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom11/command "'/usr/bin/1password --quick-access'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom11/name "'Open 1password quick access'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom12/binding "'<Super><Alt>k'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom12/command "'systemctl suspend'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom12/name "'Suspend system'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom13/binding "'<Super><Alt>r'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom13/command "'$HOME/.bin/focus-switch rebalance force'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom13/name "'Rebalance windows'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom15/binding "'<Super>z'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom15/command "'$HOME/.bin/ide'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom15/name "'Open IDE'"

# Power
echo "[gsettings] setting up power management"
gsettings set org.gnome.settings-daemon.plugins.power ambient-enabled false
gsettings set org.gnome.settings-daemon.plugins.power idle-brightness 240
gsettings set org.gnome.settings-daemon.plugins.power idle-dim true
gsettings set org.gnome.settings-daemon.plugins.power lid-close-ac-action "suspend"
gsettings set org.gnome.settings-daemon.plugins.power lid-close-battery-action "suspend"
gsettings set org.gnome.settings-daemon.plugins.power lid-close-suspend-with-external-monitor false
gsettings set org.gnome.settings-daemon.plugins.power power-button-action "nothing"
gsettings set org.gnome.settings-daemon.plugins.power power-saver-profile-on-low-battery true
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 3600
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type "suspend"
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 900
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type "suspend"

# Blur my shell
echo "[gsettings] setting shell blur"
gsettings set org.gnome.shell.extensions.blur-my-shell.appfolder blur true
gsettings set org.gnome.shell.extensions.blur-my-shell.lockscreen blur true
gsettings set org.gnome.shell.extensions.blur-my-shell.screenshot blur true
gsettings set org.gnome.shell.extensions.blur-my-shell.window-list blur true
gsettings set org.gnome.shell.extensions.blur-my-shell.panel blur true
gsettings set org.gnome.shell.extensions.blur-my-shell.overview blur true
gsettings set org.gnome.shell.extensions.blur-my-shell.overview pipeline 'pipeline_default'
gsettings set org.gnome.shell.extensions.blur-my-shell.dash-to-dock blur true
gsettings set org.gnome.shell.extensions.blur-my-shell.dash-to-dock brightness 0.6
gsettings set org.gnome.shell.extensions.blur-my-shell.dash-to-dock sigma 30
gsettings set org.gnome.shell.extensions.blur-my-shell.dash-to-dock static-blur true
gsettings set org.gnome.shell.extensions.blur-my-shell.dash-to-dock style-dash-to-dock 0
gsettings set org.gnome.shell.extensions.alphabetical-app-grid folder-order-position 'end'

echo "[gsettings] configuration applied successfully"
