#!/bin/bash

declare inputs=(alsa_input.pci-0000_04_00.6.analog-stereo alsa_input.usb-21102019_THRONMAX_PULSE_MICROPHONE-00.iec958-stereo)
declare outputs=(alsa_output.pci-0000_04_00.6.analog-stereo alsa_output.pci-0000_04_00.1.hdmi-stereo bluez_sink.78_2B_64_9F_C0_D3.a2dp_sink)


if [ "$1" == "input" ]; then
    input_position=$(cat /tmp/sway-audio-input)
    if [ -z "$input_position" ]; then
        input_position=0
    fi
    echo "${inputs[input_position]}"
	pactl set-default-source "${inputs[input_position]}"
    input_position=$((input_position+1))
    if [ $input_position -ge 3  ]; then
        input_position=0
    fi
    echo $input_position > /tmp/sway-audio-input
elif [ "$1" == "output" ]; then
    output_position=$(cat /tmp/sway-audio-output)
    if [ -z "$output_position" ]; then
        output_position=0
    fi
    echo "${outputs[output_position]}"
	pactl set-default-sink "${outputs[output_position]}"
    output_position=$((output_position+1))
    if [ $output_position -ge 3  ]; then
        output_position=0
    fi
    echo $output_position > /tmp/sway-audio-output
fi

