#!/usr/bin/env bash
# ADDRESS="0C:C4:13:F8:76:65" # pixel buds
ADDRESS="78:2B:64:9F:C0:D3" # bose qc45

if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "help" ]; then
	echo "Usage: $(basename $0) <cycle>"
elif [ "$1" = "cycle" ]; then
	if bluetoothctl info "$ADDRESS" | grep -q "Connected: no" >/dev/null 2>&1; then
		bluetoothctl connect "$ADDRESS"
	else
		bluetoothctl disconnect "$ADDRESS"
	fi
else
	if bluetoothctl info "$ADDRESS" | grep -q "Connected: no" >/dev/null 2>&1; then
		echo '{"text":""}'
	else
		echo '{"icon":"","state":"Good","text":""}'
	fi
fi
