#!/bin/bash
VIDECONF_WS="4: videoconf"
VIDECONF_WS_SHORT="4:"
I3_EVENT="urgent"

while true; do
	i3-msg -t subscribe -m '[ "workspace" ]' | while read -r line; do
		WS=$(echo "${line}" | jq -r ".change,.current.name")
		stringarray=(${WS})
		if [ "${stringarray[0]}" = "${I3_EVENT}" ] && [ "${stringarray[1]}" = "${VIDECONF_WS_SHORT}" ]; then
			if xrandr --listactivemonitors | grep -q DP-2-2; then
				i3-msg "[workspace=\"${VIDECONF_WS}\"]" "move workspace to output eDP; workspace ${VIDECONF_WS}"
			fi
		fi
	done
	sleep 0.5
done
