#!/usr/bin/env bash

notify() {
  notify-send --icon=display i3monitor "$@"
}

# Control the dunst daemon, if it is running.
dunst() {
  case "${1:-}" in
    set)
      if dunstctl is-paused | grep -q false; then
        notify-send "Pausing notification system"
      else
        notify-send "Resuming notification system"
      fi
      sleep 5
      dunstctl set-paused toggle
      ;;
    get)
      if dunstctl is-paused | grep -q false; then
        echo '{"icon":"","state":"Warning","text":""}'
      else
        echo '{"text":""}'
      fi
      ;;
    suspend)
      if dunstctl is-paused | grep -q false; then
        notify-send "Pausing notification system"
        sleep 5
        dunstctl set-paused true 
      fi
      ;;
    resume)
      if dunstctl is-paused | grep -q true; then
        dunstctl set-paused false
        notify-send "Resuming notification system"
      fi
      ;;
    *)
      echo "Usage: $0 dunst suspend|resume|get|set"
      exit 2
      ;;
  esac
}

lock() {
  dunst suspend
  dbus-send --type=method_call --dest=org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock
  sleep 5
  dunst resume
}

case "${1:-}" in
  lock)
    lock
    ;;
  logout)
    gnome-session-quit --logout
    ;;
  suspend)
    lock
    systemctl suspend -i
    ;;
  hibernate)
    lock
    systemctl hibernate -i
    ;;
  reboot)
    gnome-session-quit --reboot
    ;;
  shutdown)
    gnome-session-quit --poweroff
    ;;
  dunst)
    dunst "${2}"
    ;;
  *)
    echo "Usage: $0 lock|logout|suspend|hibernate|reboot|shutdown|dunst"
    exit 2
    ;;
esac

exit 0
