#!/bin/bash

load=$(awk '{print $2}' /proc/loadavg)

if (( $(echo "$load > 12" |bc -l) )); then
	echo "{\"text\": \"$load\", \"alt\": \"\", \"tooltip\": false, \"class\": \"high\", \"percentage\": \"\"}"
elif (( $(echo "$load > 8" |bc -l) )); then
	echo "{\"text\": \"$load\", \"alt\": \"\", \"tooltip\": false, \"class\": \"medium\", \"percentage\": \"\"}"
else
	echo "{\"text\": \"$load\", \"alt\": \"\", \"tooltip\": false, \"class\": \"low\", \"percentage\": \"\"}"
fi
