#!/bin/bash

usage() {
	echo "usage $0 auto|laptop|home|ita|work|mirror|startup|key|fix"
	exit 2
}

source "$HOME/.config/crisidev-common"
setup_zsh_paths

mode=${1}

case "$mode" in
auto)
	autorandr_safe --change --force
	;;
laptop)
	autorandr_safe --load laptop
	;;
home)
	autorandr_safe --load home
	;;
ita)
	autorandr_safe --load ita
	;;
work)
	autorandr_safe --load work
	;;
mirror)
	mirror_display
	;;
startup)
	setup_keyboard_speed
	add_resolutions

	# "workspace 3:  ; exec --no-startup-id kitty $HOME/.bin/irc"
	declare -a arr=(
		"workspace 5:  ; exec --no-startup-id google-chrome --user-data-dir=$HOME/.local/share/chrome-chime --disable-session-crashed-bubble -app=https://app.chime.aws"
		"workspace 6:  ; exec --no-startup-id env GTK_THEME=Yaru-purple evolution -c mail; exec --no-startup-id env GTK_THEME=Yaru-purple evolution -c calendar"
		"workspace 8:  ; exec --no-startup-id google-chrome --user-data-dir=$HOME/.local/share/chrome-whatsapp --disable-session-crashed-bubble -app=https://web.whatsapp.com; exec --no-startup-id signal-desktop"
		"workspace 9:  ; exec --no-startup-id slack"
		"workspace 2:  ; exec --no-startup-id firefox"
	)
	i3_msg_dispatcher "${arr[@]}"
	sleep 5
	autorandr --change --force
	setup_keyboard_speed
	;;
key)
	setup_keyboard_speed
	;;
*)
	usage
	;;
esac

exit 0
