#!/bin/bash

usage() {
  echo "usage $0 auto|laptop|home|ita|work|mirror|startup|key|fix"
  exit 2
}

source "$HOME/.config/crisidev-common"

mode=${1}

case "$mode" in
  auto)
    autorandr --change
    ;;
  laptop)
    autorandr --load laptop --force
    xrandr --output HDMI-A-0 --off
    ;;
  home)
    autorandr --load home --force
    ;;
  ita)
    autorandr --load ita --force
    ;;
  work)
    autorandr --load work --force
    ;;
  mirror)
    mirror_display
    ;;
  startup)
    setup_keyboard_speed
    add_resolutions
    declare -a arr=(
      "workspace 1: shell; exec kitty --detach"
      "workspace 2: www; exec --no-startup-id firefox"
      "workspace 3: irc; exec kitty --detach"
      "workspace 5: chime; exec --no-startup-id google-chrome --user-data-dir=$HOME/.local/share/chrome-chime --disable-session-crashed-bubble -app=https://app.chime.aws"
      "workspace 6: mail; exec --no-startup-id env GTK_THEME=Adwaita evolution -c mail; exec --no-startup-id  env GTK_THEME=Adwaita evolution -c calendar"
      "workspace 8: chat; exec --no-startup-id google-chrome --user-data-dir=$HOME/.local/share/chrome-whatsapp --disable-session-crashed-bubble -app=https://web.whatsapp.com; exec --no-startup-id signal-desktop"
      "workspace 9: slack; exec --no-startup-id slack"
      "workspace 11: spotify; exec --no-startup-id spotify"
      "workspace 2: www"
    )
    i3_msg_dispatcher "${arr[@]}"
    sleep 5
    autorandr --change --force
    setup_keyboard_speed
    ;;
  key)
    setup_keyboard_speed
    ;;
  *)
    usage
    ;;
esac

exit 0
