#!/usr/bin/env bash

usage() {
	echo "usage: $0 [toggle]"
	exit 2
}

multigrid=""
if [ "$1" = "-m" ]; then
	multigrid=--multigrid
	shift
fi

# paths
export GOPATH=~/.go
export PATH=~/.bin:~/.toolbox/bin:~/.pyenv/bin:~/.rbenv/bin:~/.nodenv/bin:~/.nodenv/versions/15.5.1/bin:~/.bin:$GOPATH/bin:~/.cargo/bin:$PATH
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-$HOME/.config/lvim}"
export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-$HOME/.local/share/lunarvim}"

start_neovide() {
	shift
	NVIM_LISTEN_ADDRESS=/tmp/nvimsocket neovide $multigrid -- -u ~/.local/share/lunarvim/lvim/init.lua -c 'let g:guifont="FiraCode Nerd Font Mono:h10"' "$@"
}

start_glrnvim() {
	shift
	NVIM_LISTEN_ADDRESS=/tmp/nvimsocket glrnvim "$@"

}

start_ide_terminal() {
	shift
	NVIM_LISTEN_ADDRESS=/tmp/nvimsocket lvim "$@"
}

if [ "$1" = "--help" ]; then
	usage
elif [ "$1" = "toggle" ]; then
	shift
	if ! i3-msg '[class="^ide$"]' scratchpad show >/dev/null 2>&1; then
		start_ide ide "$@"
		sleep 1
		i3-msg '[class="^ide$"]' "move position center move scratchpad scratchpad show" >/dev/null 2>&1
	fi
elif [ "$1" = "new" ]; then
	start_glrnvim "$@"
elif [ "$1" = "term" ]; then
	start_ide_terminal "$@"
else
	nvr --remote "$@"
fi

exit 0
