#!/usr/bin/env bash

# set -x
set -e -o pipefail

# Functions
usage() {
	echo "usage: $0 toggle|new|<filenames..>"
	exit 2
}

NVIM_LISTEN_ADDRESS=/tmp/nvimsocket
MY_PATH="$HOME/.bin:$HOME/.local/share/nvim/mason/bin"
BREW_PATH="/opt/homebrew/bin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/opt/grep/libexec/gnubin:/opt/homebrew/opt/ssh-copy-id/bin"
SYSTEM_PATH="/usr/local/bin"
export PATH="$MY_PATH:$BREW_PATH:$SYSTEM_PATH:$PATH"
export RUSTC_WRAPPER=/opt/homebrew/bin/sccache
eval "$(mise activate bash --shims)"

# Start neovim IDE using class `ide` and listening on $NVIM_LISTEN_ADDRESS
function start_ide() {
	[ -f "$HOME/.zsh_secrets" ] && source "$HOME/.zsh_secrets"
	[ -f "$HOME/.zsh_private" ] && source "$HOME/.zsh_private"
	exec /Applications/Neovide.app/Contents/MacOS/Neovide -- --listen "$NVIM_LISTEN_ADDRESS" "$@"
}

# Open a file inside the running IDE.
function open_in_ide() {
	if ! pgrep -f "Neovide" >/dev/null; then
		start_ide "$@"
		sleep 0.5
	fi
	exec nvr --remote "$@"
}

# main switch
case $1 in
--help)
	usage
	;;
new)
	shift
	start_ide "$@"
	;;
*)
	open_in_ide "$@"
	;;
esac

exit 0
