#!/bin/bash

if [ "$1" == "set" ]; then
  pactl set-source-mute @DEFAULT_SOURCE@ toggle
elif [ "$1" == "get" ]; then
  if pactl list sources | grep -q 'Mute: yes'; then
    echo '{"icon":"","state":"Info","text":""}'
  else
    echo '{"icon":"","state":"Critical","text":""}'
  fi
fi
