#!/usr/bin/env bash

export STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.local/share/Steam 
export STEAM_COMPAT_DATA_PATH=/home/deck/.proton 
exec /home/deck/.steam/steam/steamapps/common/Proton\ 7.0/proton run "$@"
