#!/bin/bash

silicon --theme ~/.config/bat/themes/tokyonight.nvim/extras/sublime/tokyonight_storm.tmTheme --font "MonoLisa Nerd Font" --background "#202228" --shadow-color "#000000" \
    --line-pad 0 --pad-horiz 20 --pad-vert 20 --shadow-blur-radius 0 --shadow-offset-x 0 --shadow-offset-y 0 "$@"
