#!/bin/sh
echo -e "\033];smux\007" > /dev/null

if [ "X${1}" = "X" ] || [ $# -lt 1 ]; then
    echo "usage: `basename $0` <host>"
    exit 1
fi


if [ "X${SSH_AUTH_SOCK}" = "X" ]; then
        eval `ssh-agent -s`
fi

#AUTOSSH_POLL=20
AUTOSSH_PORT=$(awk 'BEGIN { srand(); do r = rand()*32000; while ( r < 20000 ); printf("%d\n",r)  }' < /dev/null)
#AUTOSSH_GATETIME=60
#AUTOSSH_LOGFILE=$HOST.log
#AUTOSSH_DEBUG=yes
#AUTOSSH_PATH=/usr/local/bin/ssh
export LANG="en_US.UTF-8"
export TERM="xterm-256color"
export AUTOSSH_POLL AUTOSSH_LOGFILE AUTOSSH_DEBUG AUTOSSH_PATH AUTOSSH_GATETIME AUTOSSH_PORT

# Start autossh
autossh -t ${1}

exit 0
