#!/usr/bin/env python

import time
import argparse
from http.server import BaseHTTPRequestHandler, HTTPServer

sleep = 1000


class testHTTPServer_RequestHandler(BaseHTTPRequestHandler):

    def do_GET(self):
        time.sleep(1000)

    def do_POST(self):
        time.sleep(1000)


def main():
    global sleep
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--port', default=28282, type=int)
    parser.add_argument('-l', '--listen', default='127.0.0.1')
    parser.add_argument('-s', '--sleep', default=1000, type=int)
    args = parser.parse_args()

    sleep = args.sleep

    server_address = (args.listen, args.port)
    httpd = HTTPServer(server_address, testHTTPServer_RequestHandler)
    print('running server on http://{}:{}, max sleep: {}'.format(args.listen, args.port, args.sleep))
    httpd.serve_forever()


if __name__ == '__main__':
    main()
