return {
    ok = "􀆅",
    loading = "􀖇",
    apple = "􀣺",
    preferences = "􀺽",
    activity = "􀒓",
    lock = "􀒳",
    brew = "􀐛",
    knob = "􀀁",
    space = "􀆊",
    github = "󰊤",
    gitlab = "󰮠",
    chat = "󱋊",
    power = {
        sleep = "󰤄",
        poweroff = "󰐥",
        reboot = "󰜉",
        lock = "󰷛",
    },
    bell = {
        default = "􀋚 ",
        dot = "􀝗 ",
    },
    git = {
        issue = "􀍷",
        discussion = "􀒤",
        pull_request = "􀙡",
        commit = "􀡚",
        indicator = "􀂓",
    },
    spotify = {
        player = "􁁒",
        play = "􀊄",
        back = "􀊎",
        play_pause = "􀊔",
        pause = "􀊆",
        next = "􀊐",
        shuffle = "􀊝",
        _repeat = "􀊞",
    },
    yabai = {
        stack = "􀏭",
        fullscreen_zoom = "􀏜",
        parent_zoom = "􀥃",
        float = "􀢌",
        grid = "􀧍",
    },
    battery = {
        _100 = "􀛨",
        _75 = "􀺸",
        _50 = "􀺶",
        _25 = "􀛩",
        _0 = "􀛪",
        _charging = "􀢋",
    },
    volume = {
        _100 = "􀊩",
        _66 = "􀊧",
        _33 = "􀊥",
        _10 = "􀊡",
        _0 = "􀊣",
    },
    wifi = {
        connected = "􀙇",
        disconnected = "􀙈",
    },
    mic = {
        on = "󰍬",
        off = "󰍭",
    },
    tailscale = {
        on = "󰞉",
        off = "󰕑",
    },
    warning = "",
    svim = {
        normal = "􀂯",
        insert = "􀂥",
        visual = "􀂿",
        cmd = "􀂙",
        pending = "􀈏",
    },
}
