#!/bin/bash

# Crisidev git configs
direnvrc_git_crisidev="$(cd $(dirname $BASH_SOURCE) &> /dev/null; pwd)/direnvrc-git-crisidev"
if [ -f "$direnvrc_git_crisidev" ]; then
    source "$direnvrc_git_crisidev"
fi
unset direnvrc_git_crisidev

# home home configs
direnvrc_git_bigo="$(cd $(dirname $BASH_SOURCE) &> /dev/null; pwd)/direnvrc-git-bigo"
if [ -f "$direnvrc_git_bigo" ]; then
    source "$direnvrc_git_bigo"
fi
unset direnvrc_git_bigo

direnvrc_git_omniva="$(cd $(dirname $BASH_SOURCE) &> /dev/null; pwd)/direnvrc-git-omniva"
if [ -f "$direnvrc_git_omniva" ]; then
    source "$direnvrc_git_omniva"
fi
unset direnvrc_git_omniva
