font = "MonoLisa Nerd Font Light 8"
height = 17
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0
separator_width = 1.0
tags_r = 0.0
tags_padding = 10.0
blocks_r = 0.0
blocks_overlap = 0.0
hide_inactive_tags = true
invert_touchpad_scrolling = true
show_layout_name = true

background = "#24283b"
color = "#c0caf5"
separator = "#c0caf5"
tag_fg = "#c0caf5"
tag_bg = "#24283b"
tag_focused_fg = "#ffffff"
tag_focused_bg = "#7aa2f7"
tag_urgent_fg = "#ffffff"
tag_urgent_bg = "#bb9af7"
tag_inactive_fg = "#c0caf5"
tag_inactive_bg = "#24283b"

command = "i3status-rs ~/.config/i3status-rs/top.toml"
position = "top" # either "top" or "bottom"

[workspaces]
1 = ""
2 = ""
3 = ""
4 = "󰒱"
5 = "󰙯"
6 = ""
7 = ""
